create TABLE IF NOT EXISTS users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar(150) NOT NULL,
	email varchar(150) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id)
);


create TABLE IF NOT EXISTS requests (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	description varchar(250) NULL,
	requestor_id BIGINT NULL,
	created timestamp NULL,
	CONSTRAINT requests_pk PRIMARY KEY (id),
	CONSTRAINT requests_users_fk FOREIGN KEY (requestor_id) REFERENCES public.users(id)
);


create TABLE IF NOT EXISTS items (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar(150) NOT NULL,
	description varchar(250) NULL,
	is_available bool NULL,
	owner_id BIGINT NOT NULL,
	request_id BIGINT NULL,
	CONSTRAINT items_pk PRIMARY KEY (id),
	CONSTRAINT items_requests_fk FOREIGN KEY (request_id) REFERENCES public.requests(id),
	CONSTRAINT items_users_fk FOREIGN KEY (owner_id) REFERENCES public.users(id)
);



create TABLE IF NOT EXISTS bookings (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	start_date timestamp NULL,
	end_date timestamp NULL,
	item_id BIGINT NOT NULL,
	booker_id BIGINT NULL,
	status varchar(15) NULL,
	CONSTRAINT bookings_pk PRIMARY KEY (id),
	CONSTRAINT bookings_start_end_check CHECK ((start_date < end_date)),
	CONSTRAINT bookings_items_fk FOREIGN KEY (item_id) REFERENCES public.items(id),
	CONSTRAINT bookings_users_fk FOREIGN KEY (booker_id) REFERENCES public.users(id)
);


create TABLE IF NOT EXISTS "comments" (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"text" varchar(250) NOT NULL,
	item_id BIGINT NOT NULL,
	author_id BIGINT NOT NULL,
	created timestamp NOT NULL,
	CONSTRAINT comments_pk PRIMARY KEY (id),
	CONSTRAINT comments_items_fk FOREIGN KEY (item_id) REFERENCES public.items(id),
	CONSTRAINT comments_users_fk FOREIGN KEY (author_id) REFERENCES public.users(id)
);