-- public.users definition

-- Drop table

-- DROP TABLE public.users;

create TABLE IF NOT EXISTS users (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(150) NOT NULL,
	email varchar(150) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id)
);


-- public.requests definition

-- Drop table

-- DROP TABLE public.requests;

create TABLE IF NOT EXISTS requests (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(250) NULL,
	requestor_id int4 NULL,
	created timestamp NULL,
	CONSTRAINT requests_pk PRIMARY KEY (id),
	CONSTRAINT requests_users_fk FOREIGN KEY (requestor_id) REFERENCES public.users(id)
);


-- public.items definition

-- Drop table

-- DROP TABLE public.items;

create TABLE IF NOT EXISTS items (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(150) NOT NULL,
	description varchar(250) NULL,
	is_available bool NULL,
	owner_id int4 NOT NULL,
	request_id int4 NULL,
	CONSTRAINT items_pk PRIMARY KEY (id),
	CONSTRAINT items_requests_fk FOREIGN KEY (request_id) REFERENCES public.requests(id),
	CONSTRAINT items_users_fk FOREIGN KEY (owner_id) REFERENCES public.users(id)
);


-- public.bookings definition

-- Drop table

-- DROP TABLE public.bookings;

create TABLE IF NOT EXISTS bookings (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	start_date timestamp NULL,
	end_date timestamp NULL,
	item_id int4 NOT NULL,
	booker_id int4 NULL,
	status varchar(15) NULL,
	CONSTRAINT bookings_pk PRIMARY KEY (id),
	CONSTRAINT bookings_start_end_check CHECK ((start_date < end_date)),
	CONSTRAINT bookings_items_fk FOREIGN KEY (item_id) REFERENCES public.items(id),
	CONSTRAINT bookings_users_fk FOREIGN KEY (booker_id) REFERENCES public.users(id)
);


-- public."comments" definition

-- Drop table

-- DROP TABLE public."comments";

create TABLE IF NOT EXISTS "comments" (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"text" varchar(250) NOT NULL,
	item_id int4 NOT NULL,
	author_id int4 NOT NULL,
	created timestamp NOT NULL,
	CONSTRAINT comments_pk PRIMARY KEY (id),
	CONSTRAINT comments_items_fk FOREIGN KEY (item_id) REFERENCES public.items(id),
	CONSTRAINT comments_users_fk FOREIGN KEY (author_id) REFERENCES public.users(id)
);